remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

name: Wes Barnett, PhD
include: [".well-known"]

minimal_mistakes_skin: "default"

author:
  name: "Wes Barnett, PhD"
  bio: "Machine Learning Engineer · PhD, Engineering · AI/ML · MLOps"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wesbarnett"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/wesbarnett"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://fosstodon.org/@barnett"
    - label: "Pixelfed"
      icon: "fas fa-fw fa-camera"
      url: "https://pixelfed.social/barnett"
    - label: "Keyoxide"
      icon: "fas fa-fw fa-key"
      url: "https://keyoxide.org/hkp/F7B28C61944FE30DABEEB0B01070BCC98C18BD66"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wesbarnett"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/wesbarnett"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://fosstodon.org/@barnett"
